### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/cxf/jaxws/JaxWsProxyFactoryBean

### ISSUE THREAD

**Issue by carlosthe19916** [project-openubl/xsender#14]
***Pregunta copiada de otra fuente:***

"Estoy intentanto usar libreria xml-sender-ws-2.1.1.Final.jar pero me sale el siguiente error
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/cxf/jaxws/JaxWsProxyFactoryBean
	at io.github.project.openubl.xmlsenderws.webservices.wrappers.SunatServiceFactory.initInstance(SunatServiceFactory.java:67)
	at io.github.project.openubl.xmlsenderws.webservices.wrappers.SunatServiceFactory.getInstance(SunatServiceFactory.java:59)
	at io.github.project.openubl.xmlsenderws.webservices.wrappers.BillServiceWrapper.sendBill(BillServiceWrapper.java:32)
	at io.github.project.openubl.xmlsenderws.webservices.providers.DefaultBillServiceProvider.sendBill(DefaultBillServiceProvider.java:136)
	at io.github.project.openubl.xmlsenderws.webservices.managers.BillServiceManager.sendBill(BillServiceManager.java:63)
	at io.github.project.openubl.xmlsenderws.webservices.managers.BillServiceManager.sendBill(BillServiceManager.java:53)
	at io.github.project.openubl.xmlsenderws.webservices.managers.BillServiceManager.sendBill(BillServiceManager.java:45)
	at key_jsic.Key_jsic_envio.main(Key_jsic_envio.java:35)
Caused by: java.lang.ClassNotFoundException: org.apache.cxf.jaxws.JaxWsProxyFactoryBean
```

Y me gustaria saber cómo resolverlo. Descargué la librería de este link https://github.com/project-openubl/xml-sender-ws/tree/2.1.1.Final"

**Comment by carlosthe19916** [comment]
Esto indica que en efecto no tienes la clase `org/apache/cxf/jaxws/JaxWsProxyFactoryBean` dentro de las dependencias de tu proyecto. La libreria xml-sender-ws también depende de otras librerias y estas también deben de estar presentes en tu proyecto. Te recomiendo importar la libreria utilizando un gestor de dependencias como Maven o Gradle y luego utilizar xml-sender-ws como se indica en el siguiente link: https://mvnrepository.com/artifact/io.github.project-openubl/xml-sender-ws
